# Generated by Django 3.2.4 on 2021-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210628_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_price',
            field=models.IntegerField(max_length=50),
        ),
    ]
