# Generated by Django 3.2.4 on 2021-06-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210628_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restraunt',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restraunt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.restraunt'),
        ),
    ]
