# Generated by Django 3.2.4 on 2021-06-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_image',
            field=models.ImageField(default='default.jpg', upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='restraunt_image',
            field=models.ImageField(default='default.jpg', upload_to='restraunt_images/'),
        ),
    ]
