# Generated by Django 3.2.4 on 2021-06-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Item',
        ),
    ]
